services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: npm run dev
    mem_limit: 1g      # Limit memory usage to 1 GB
    cpus: 1.0          # Limit to 1 CPU core
    # volumes:
    #   - .:/app                 # Mount host app code
    #   - ./node_modules:/app/node_modules      # Preserve container-installed node_modules
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    env_file:
      - .env
volumes:
  node_modules:
