services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: npm run dev
    mem_limit: 1g      # Limit memory usage to 1 GB
    cpus: 1.0          # Limit to 1 CPU core

volumes:
  node_modules:

