services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: npm run dev
    mem_limit: 1g      # Limit memory usage to 1 GB
    cpus: 1.0          # Limit to 1 CPU core
    volumes:
    - .:/app                 # Mount host app code
    - /app/node_modules      # Preserve container-installed node_modules

